server:
  port: 8080
#  error:
#    whitelabel:
#      enabled: false


spring:
  autoconfigure:
    exclude[0]: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/demonou #change this to your database url
    password: root #change this to your database username
    username: root #change this to your database password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mvc:
    throw-exception-if-no-handler-found: true

  resources:
#    add-mappings: false